# config.yaml
port: 8086
default_threshold_shares: 20000
sound_file: "./web/sounds/hey.mp3"
cooldown_seconds: 1
smart_depth: true
levels_to_scan: 10
price_reference: "best_ask"
log_level: "info"
ibkr_gateway_url: "https://127.0.0.1:5000"
session_store_path: "./data/session.json"


